// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: deputy.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// task list
type Task int32

const (
	Task_help   Task = 0
	Task_list   Task = 1
	Task_goto   Task = 2
	Task_save   Task = 3
	Task_remove Task = 4
	Task_hello  Task = 8
	Task_exit   Task = 999
)

// Enum value maps for Task.
var (
	Task_name = map[int32]string{
		0:   "help",
		1:   "list",
		2:   "goto",
		3:   "save",
		4:   "remove",
		8:   "hello",
		999: "exit",
	}
	Task_value = map[string]int32{
		"help":   0,
		"list":   1,
		"goto":   2,
		"save":   3,
		"remove": 4,
		"hello":  8,
		"exit":   999,
	}
)

func (x Task) Enum() *Task {
	p := new(Task)
	*p = x
	return p
}

func (x Task) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Task) Descriptor() protoreflect.EnumDescriptor {
	return file_deputy_proto_enumTypes[0].Descriptor()
}

func (Task) Type() protoreflect.EnumType {
	return &file_deputy_proto_enumTypes[0]
}

func (x Task) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Task.Descriptor instead.
func (Task) EnumDescriptor() ([]byte, []int) {
	return file_deputy_proto_rawDescGZIP(), []int{0}
}

// Format defines the options
type Format int32

const (
	// deputy output yaml
	Format_YAML Format = 0
	// deputy output json
	Format_JSON Format = 1
	// deputy output xml
	Format_XML Format = 2
	// MAX
	Format_FORMAT_LEN Format = 3
)

// Enum value maps for Format.
var (
	Format_name = map[int32]string{
		0: "YAML",
		1: "JSON",
		2: "XML",
		3: "FORMAT_LEN",
	}
	Format_value = map[string]int32{
		"YAML":       0,
		"JSON":       1,
		"XML":        2,
		"FORMAT_LEN": 3,
	}
)

func (x Format) Enum() *Format {
	p := new(Format)
	*p = x
	return p
}

func (x Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Format) Descriptor() protoreflect.EnumDescriptor {
	return file_deputy_proto_enumTypes[1].Descriptor()
}

func (Format) Type() protoreflect.EnumType {
	return &file_deputy_proto_enumTypes[1]
}

func (x Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Format.Descriptor instead.
func (Format) EnumDescriptor() ([]byte, []int) {
	return file_deputy_proto_rawDescGZIP(), []int{1}
}

// Projection defines the level of detail
// that is presented
type Projection int32

const (
	// no reduction
	Projection_FULL Projection = 0
	// less detail than full
	Projection_SUMMARY Projection = 1
	// key, value pair
	Projection_BRIEF Projection = 2
	// MAX
	Projection_PROJECTION_LEN Projection = 3
)

// Enum value maps for Projection.
var (
	Projection_name = map[int32]string{
		0: "FULL",
		1: "SUMMARY",
		2: "BRIEF",
		3: "PROJECTION_LEN",
	}
	Projection_value = map[string]int32{
		"FULL":           0,
		"SUMMARY":        1,
		"BRIEF":          2,
		"PROJECTION_LEN": 3,
	}
)

func (x Projection) Enum() *Projection {
	p := new(Projection)
	*p = x
	return p
}

func (x Projection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Projection) Descriptor() protoreflect.EnumDescriptor {
	return file_deputy_proto_enumTypes[2].Descriptor()
}

func (Projection) Type() protoreflect.EnumType {
	return &file_deputy_proto_enumTypes[2]
}

func (x Projection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Projection.Descriptor instead.
func (Projection) EnumDescriptor() ([]byte, []int) {
	return file_deputy_proto_rawDescGZIP(), []int{2}
}

// values for 'auto' features
type Auto int32

const (
	// turn off auto
	Auto_OFF Auto = 0
	// auto reply yes
	Auto_Y Auto = 1
	// auto reply no
	Auto_N Auto = 2
	// MAX
	Auto_AUTO_LEN Auto = 3
)

// Enum value maps for Auto.
var (
	Auto_name = map[int32]string{
		0: "OFF",
		1: "Y",
		2: "N",
		3: "AUTO_LEN",
	}
	Auto_value = map[string]int32{
		"OFF":      0,
		"Y":        1,
		"N":        2,
		"AUTO_LEN": 3,
	}
)

func (x Auto) Enum() *Auto {
	p := new(Auto)
	*p = x
	return p
}

func (x Auto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Auto) Descriptor() protoreflect.EnumDescriptor {
	return file_deputy_proto_enumTypes[3].Descriptor()
}

func (Auto) Type() protoreflect.EnumType {
	return &file_deputy_proto_enumTypes[3]
}

func (x Auto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Auto.Descriptor instead.
func (Auto) EnumDescriptor() ([]byte, []int) {
	return file_deputy_proto_rawDescGZIP(), []int{3}
}

type Feature_Flag int32

const (
	// format
	Feature_f Feature_Flag = 0
	// projection (d for detail)
	Feature_d Feature_Flag = 1
	// auto reply
	Feature_auto Feature_Flag = 2
)

// Enum value maps for Feature_Flag.
var (
	Feature_Flag_name = map[int32]string{
		0: "f",
		1: "d",
		2: "auto",
	}
	Feature_Flag_value = map[string]int32{
		"f":    0,
		"d":    1,
		"auto": 2,
	}
)

func (x Feature_Flag) Enum() *Feature_Flag {
	p := new(Feature_Flag)
	*p = x
	return p
}

func (x Feature_Flag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Feature_Flag) Descriptor() protoreflect.EnumDescriptor {
	return file_deputy_proto_enumTypes[4].Descriptor()
}

func (Feature_Flag) Type() protoreflect.EnumType {
	return &file_deputy_proto_enumTypes[4]
}

func (x Feature_Flag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Feature_Flag.Descriptor instead.
func (Feature_Flag) EnumDescriptor() ([]byte, []int) {
	return file_deputy_proto_rawDescGZIP(), []int{6, 0}
}

// Deputy
type Deputy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// label assigned to this deputy version
	Label string `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	// version of release
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// ordered list of skills
	Skills []*Skill `protobuf:"bytes,2,rep,name=skills,proto3" json:"skills,omitempty"`
	// skills map keyed on tasks and alternates
	Skillset *Skillset `protobuf:"bytes,3,opt,name=skillset,proto3" json:"skillset,omitempty"`
	// models mapped to routes
	Dictionary *Dictionary `protobuf:"bytes,4,opt,name=dictionary,proto3" json:"dictionary,omitempty"`
	// ordered list of skills
	Features []*Feature `protobuf:"bytes,7,rep,name=features,proto3" json:"features,omitempty"`
	// features map keyed on feature flag and label
	Gallery *Gallery `protobuf:"bytes,5,opt,name=gallery,proto3" json:"gallery,omitempty"`
}

func (x *Deputy) Reset() {
	*x = Deputy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deputy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deputy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deputy) ProtoMessage() {}

func (x *Deputy) ProtoReflect() protoreflect.Message {
	mi := &file_deputy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deputy.ProtoReflect.Descriptor instead.
func (*Deputy) Descriptor() ([]byte, []int) {
	return file_deputy_proto_rawDescGZIP(), []int{0}
}

func (x *Deputy) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Deputy) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Deputy) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *Deputy) GetSkillset() *Skillset {
	if x != nil {
		return x.Skillset
	}
	return nil
}

func (x *Deputy) GetDictionary() *Dictionary {
	if x != nil {
		return x.Dictionary
	}
	return nil
}

func (x *Deputy) GetFeatures() []*Feature {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *Deputy) GetGallery() *Gallery {
	if x != nil {
		return x.Gallery
	}
	return nil
}

// skill mapped to skills' tasks and alternates
type Skillset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AliasMap map[string]*Skill `protobuf:"bytes,1,rep,name=alias_map,json=aliasMap,proto3" json:"alias_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Skillset) Reset() {
	*x = Skillset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deputy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Skillset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skillset) ProtoMessage() {}

func (x *Skillset) ProtoReflect() protoreflect.Message {
	mi := &file_deputy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skillset.ProtoReflect.Descriptor instead.
func (*Skillset) Descriptor() ([]byte, []int) {
	return file_deputy_proto_rawDescGZIP(), []int{1}
}

func (x *Skillset) GetAliasMap() map[string]*Skill {
	if x != nil {
		return x.AliasMap
	}
	return nil
}

// Skill in the skillset.
type Skill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the task this skill effects
	Task string `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	// alternate codes for the task
	Alternates []string `protobuf:"bytes,2,rep,name=alternates,proto3" json:"alternates,omitempty"`
	// description of skill
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// summary of usage
	Summary *Summary `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
}

func (x *Skill) Reset() {
	*x = Skill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deputy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_deputy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_deputy_proto_rawDescGZIP(), []int{2}
}

func (x *Skill) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *Skill) GetAlternates() []string {
	if x != nil {
		return x.Alternates
	}
	return nil
}

func (x *Skill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Skill) GetSummary() *Summary {
	if x != nil {
		return x.Summary
	}
	return nil
}

// Summary description of model
type Summary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Usage    string   `protobuf:"bytes,1,opt,name=usage,proto3" json:"usage,omitempty"`
	Syntax   string   `protobuf:"bytes,2,opt,name=syntax,proto3" json:"syntax,omitempty"`
	Examples []string `protobuf:"bytes,3,rep,name=examples,proto3" json:"examples,omitempty"`
}

func (x *Summary) Reset() {
	*x = Summary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deputy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_deputy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_deputy_proto_rawDescGZIP(), []int{3}
}

func (x *Summary) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *Summary) GetSyntax() string {
	if x != nil {
		return x.Syntax
	}
	return ""
}

func (x *Summary) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

// Command to the deputy
type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// task to carry out
	Task string `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	// where to do the task
	Location string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	// how to present the outcome
	Presentation *Presentation `protobuf:"bytes,3,opt,name=presentation,proto3" json:"presentation,omitempty"`
	// reasons order not carried out
	Excuse string `protobuf:"bytes,4,opt,name=excuse,proto3" json:"excuse,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deputy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_deputy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_deputy_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *Command) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Command) GetPresentation() *Presentation {
	if x != nil {
		return x.Presentation
	}
	return nil
}

func (x *Command) GetExcuse() string {
	if x != nil {
		return x.Excuse
	}
	return ""
}

// Gallery of features keyed to flags and labels
type Gallery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlagMap map[string]*Feature `protobuf:"bytes,1,rep,name=flag_map,json=flagMap,proto3" json:"flag_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Gallery) Reset() {
	*x = Gallery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deputy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gallery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gallery) ProtoMessage() {}

func (x *Gallery) ProtoReflect() protoreflect.Message {
	mi := &file_deputy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gallery.ProtoReflect.Descriptor instead.
func (*Gallery) Descriptor() ([]byte, []int) {
	return file_deputy_proto_rawDescGZIP(), []int{5}
}

func (x *Gallery) GetFlagMap() map[string]*Feature {
	if x != nil {
		return x.FlagMap
	}
	return nil
}

// Feature can describes how to respond to input and
// how to present the output.
type Feature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// flag to indicate feature
	Flag string `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	// unique label to reference feature
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// unique label to reference feature
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// usage summary
	Summary *Summary `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
}

func (x *Feature) Reset() {
	*x = Feature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deputy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feature) ProtoMessage() {}

func (x *Feature) ProtoReflect() protoreflect.Message {
	mi := &file_deputy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feature.ProtoReflect.Descriptor instead.
func (*Feature) Descriptor() ([]byte, []int) {
	return file_deputy_proto_rawDescGZIP(), []int{6}
}

func (x *Feature) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *Feature) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Feature) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Feature) GetSummary() *Summary {
	if x != nil {
		return x.Summary
	}
	return nil
}

// Presentation defines the features
// used to present output and respond to input
type Presentation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Format to present (yaml,json,xml)
	Format Format `protobuf:"varint,1,opt,name=format,proto3,enum=centretown.sketchit.v1.Format" json:"format,omitempty"`
	// Projection detail (full,summary,brief)
	Projection []Projection `protobuf:"varint,2,rep,packed,name=projection,proto3,enum=centretown.sketchit.v1.Projection" json:"projection,omitempty"`
	// Auto reply to confirmations. (off,y,n)
	Confirm Auto `protobuf:"varint,3,opt,name=confirm,proto3,enum=centretown.sketchit.v1.Auto" json:"confirm,omitempty"`
}

func (x *Presentation) Reset() {
	*x = Presentation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deputy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Presentation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Presentation) ProtoMessage() {}

func (x *Presentation) ProtoReflect() protoreflect.Message {
	mi := &file_deputy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Presentation.ProtoReflect.Descriptor instead.
func (*Presentation) Descriptor() ([]byte, []int) {
	return file_deputy_proto_rawDescGZIP(), []int{7}
}

func (x *Presentation) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_YAML
}

func (x *Presentation) GetProjection() []Projection {
	if x != nil {
		return x.Projection
	}
	return nil
}

func (x *Presentation) GetConfirm() Auto {
	if x != nil {
		return x.Confirm
	}
	return Auto_OFF
}

var File_deputy_proto protoreflect.FileDescriptor

var file_deputy_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x65, 0x70, 0x75, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16,
	0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63,
	0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x10, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe9, 0x02, 0x0a, 0x06, 0x44, 0x65, 0x70,
	0x75, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e,
	0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x3c, 0x0a, 0x08, 0x73, 0x6b,
	0x69, 0x6c, 0x6c, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63,
	0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68,
	0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x65, 0x74, 0x52, 0x08,
	0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x65, 0x74, 0x12, 0x42, 0x0a, 0x0a, 0x64, 0x69, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63,
	0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68,
	0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79,
	0x52, 0x0a, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x3b, 0x0a, 0x08,
	0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74,
	0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x07, 0x67, 0x61, 0x6c,
	0x6c, 0x65, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x65, 0x6e,
	0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x79, 0x52, 0x07, 0x67, 0x61, 0x6c,
	0x6c, 0x65, 0x72, 0x79, 0x22, 0xb3, 0x01, 0x0a, 0x08, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x65,
	0x74, 0x12, 0x4b, 0x0a, 0x09, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77,
	0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x73, 0x65, 0x74, 0x2e, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x4d, 0x61, 0x70, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x4d, 0x61, 0x70, 0x1a, 0x5a,
	0x0a, 0x0d, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x33, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b,
	0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x98, 0x01, 0x0a, 0x05, 0x53,
	0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x6c, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x6c,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x07, 0x73, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x65,
	0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x07, 0x73, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x53, 0x0a, 0x07, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6e, 0x74, 0x61, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6e, 0x74, 0x61, 0x78, 0x12, 0x1a,
	0x0a, 0x08, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x22, 0x9b, 0x01, 0x0a, 0x07, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x48, 0x0a, 0x0c, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63,
	0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68,
	0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0c, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x63, 0x75, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x65, 0x78, 0x63, 0x75, 0x73, 0x65, 0x22, 0xaf, 0x01, 0x0a, 0x07, 0x47, 0x61, 0x6c,
	0x6c, 0x65, 0x72, 0x79, 0x12, 0x47, 0x0a, 0x08, 0x66, 0x6c, 0x61, 0x67, 0x5f, 0x6d, 0x61, 0x70,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74,
	0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x79, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x4d, 0x61, 0x70, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x66, 0x6c, 0x61, 0x67, 0x4d, 0x61, 0x70, 0x1a, 0x5b, 0x0a,
	0x0c, 0x46, 0x6c, 0x61, 0x67, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x35, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74,
	0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xb0, 0x01, 0x0a, 0x07, 0x46,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e,
	0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x1e, 0x0a,
	0x04, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x05, 0x0a, 0x01, 0x66, 0x10, 0x00, 0x12, 0x05, 0x0a, 0x01,
	0x64, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x6f, 0x10, 0x02, 0x22, 0xc2, 0x01,
	0x0a, 0x0c, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x36,
	0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e,
	0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74,
	0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x06,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x42, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x63, 0x65, 0x6e,
	0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x63, 0x65,
	0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x2a, 0x50, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x08, 0x0a, 0x04, 0x68, 0x65,
	0x6c, 0x70, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x67, 0x6f, 0x74, 0x6f, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x73, 0x61, 0x76, 0x65,
	0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x10, 0x04, 0x12, 0x09,
	0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x10, 0x08, 0x12, 0x09, 0x0a, 0x04, 0x65, 0x78, 0x69,
	0x74, 0x10, 0xe7, 0x07, 0x2a, 0x35, 0x0a, 0x06, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x08,
	0x0a, 0x04, 0x59, 0x41, 0x4d, 0x4c, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x53, 0x4f, 0x4e,
	0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x58, 0x4d, 0x4c, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x46,
	0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x4c, 0x45, 0x4e, 0x10, 0x03, 0x2a, 0x42, 0x0a, 0x0a, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x55, 0x4c,
	0x4c, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x4d, 0x4d, 0x41, 0x52, 0x59, 0x10, 0x01,
	0x12, 0x09, 0x0a, 0x05, 0x42, 0x52, 0x49, 0x45, 0x46, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x50,
	0x52, 0x4f, 0x4a, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4c, 0x45, 0x4e, 0x10, 0x03, 0x2a,
	0x2b, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x6f, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x46, 0x46, 0x10, 0x00,
	0x12, 0x05, 0x0a, 0x01, 0x59, 0x10, 0x01, 0x12, 0x05, 0x0a, 0x01, 0x4e, 0x10, 0x02, 0x12, 0x0c,
	0x0a, 0x08, 0x41, 0x55, 0x54, 0x4f, 0x5f, 0x4c, 0x45, 0x4e, 0x10, 0x03, 0x42, 0x24, 0x5a, 0x22,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x65, 0x6e, 0x74, 0x72,
	0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2f, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2f, 0x61,
	0x70, 0x69, 0x50, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_deputy_proto_rawDescOnce sync.Once
	file_deputy_proto_rawDescData = file_deputy_proto_rawDesc
)

func file_deputy_proto_rawDescGZIP() []byte {
	file_deputy_proto_rawDescOnce.Do(func() {
		file_deputy_proto_rawDescData = protoimpl.X.CompressGZIP(file_deputy_proto_rawDescData)
	})
	return file_deputy_proto_rawDescData
}

var file_deputy_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_deputy_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_deputy_proto_goTypes = []interface{}{
	(Task)(0),            // 0: centretown.sketchit.v1.Task
	(Format)(0),          // 1: centretown.sketchit.v1.Format
	(Projection)(0),      // 2: centretown.sketchit.v1.Projection
	(Auto)(0),            // 3: centretown.sketchit.v1.Auto
	(Feature_Flag)(0),    // 4: centretown.sketchit.v1.Feature.Flag
	(*Deputy)(nil),       // 5: centretown.sketchit.v1.Deputy
	(*Skillset)(nil),     // 6: centretown.sketchit.v1.Skillset
	(*Skill)(nil),        // 7: centretown.sketchit.v1.Skill
	(*Summary)(nil),      // 8: centretown.sketchit.v1.Summary
	(*Command)(nil),      // 9: centretown.sketchit.v1.Command
	(*Gallery)(nil),      // 10: centretown.sketchit.v1.Gallery
	(*Feature)(nil),      // 11: centretown.sketchit.v1.Feature
	(*Presentation)(nil), // 12: centretown.sketchit.v1.Presentation
	nil,                  // 13: centretown.sketchit.v1.Skillset.AliasMapEntry
	nil,                  // 14: centretown.sketchit.v1.Gallery.FlagMapEntry
	(*Dictionary)(nil),   // 15: centretown.sketchit.v1.Dictionary
}
var file_deputy_proto_depIdxs = []int32{
	7,  // 0: centretown.sketchit.v1.Deputy.skills:type_name -> centretown.sketchit.v1.Skill
	6,  // 1: centretown.sketchit.v1.Deputy.skillset:type_name -> centretown.sketchit.v1.Skillset
	15, // 2: centretown.sketchit.v1.Deputy.dictionary:type_name -> centretown.sketchit.v1.Dictionary
	11, // 3: centretown.sketchit.v1.Deputy.features:type_name -> centretown.sketchit.v1.Feature
	10, // 4: centretown.sketchit.v1.Deputy.gallery:type_name -> centretown.sketchit.v1.Gallery
	13, // 5: centretown.sketchit.v1.Skillset.alias_map:type_name -> centretown.sketchit.v1.Skillset.AliasMapEntry
	8,  // 6: centretown.sketchit.v1.Skill.summary:type_name -> centretown.sketchit.v1.Summary
	12, // 7: centretown.sketchit.v1.Command.presentation:type_name -> centretown.sketchit.v1.Presentation
	14, // 8: centretown.sketchit.v1.Gallery.flag_map:type_name -> centretown.sketchit.v1.Gallery.FlagMapEntry
	8,  // 9: centretown.sketchit.v1.Feature.summary:type_name -> centretown.sketchit.v1.Summary
	1,  // 10: centretown.sketchit.v1.Presentation.format:type_name -> centretown.sketchit.v1.Format
	2,  // 11: centretown.sketchit.v1.Presentation.projection:type_name -> centretown.sketchit.v1.Projection
	3,  // 12: centretown.sketchit.v1.Presentation.confirm:type_name -> centretown.sketchit.v1.Auto
	7,  // 13: centretown.sketchit.v1.Skillset.AliasMapEntry.value:type_name -> centretown.sketchit.v1.Skill
	11, // 14: centretown.sketchit.v1.Gallery.FlagMapEntry.value:type_name -> centretown.sketchit.v1.Feature
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_deputy_proto_init() }
func file_deputy_proto_init() {
	if File_deputy_proto != nil {
		return
	}
	file_dictionary_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_deputy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deputy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deputy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Skillset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deputy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Skill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deputy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Summary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deputy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deputy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gallery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deputy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Feature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deputy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Presentation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_deputy_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_deputy_proto_goTypes,
		DependencyIndexes: file_deputy_proto_depIdxs,
		EnumInfos:         file_deputy_proto_enumTypes,
		MessageInfos:      file_deputy_proto_msgTypes,
	}.Build()
	File_deputy_proto = out.File
	file_deputy_proto_rawDesc = nil
	file_deputy_proto_goTypes = nil
	file_deputy_proto_depIdxs = nil
}
