// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: sketch.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ActionType int32

const (
	ActionType_delay ActionType = 0
	ActionType_mode  ActionType = 1
	ActionType_pin   ActionType = 2
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "delay",
		1: "mode",
		2: "pin",
	}
	ActionType_value = map[string]int32{
		"delay": 0,
		"mode":  1,
		"pin":   2,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_sketch_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_sketch_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{0}
}

type Signal int32

const (
	Signal_analog  Signal = 0
	Signal_digital Signal = 1
)

// Enum value maps for Signal.
var (
	Signal_name = map[int32]string{
		0: "analog",
		1: "digital",
	}
	Signal_value = map[string]int32{
		"analog":  0,
		"digital": 1,
	}
)

func (x Signal) Enum() *Signal {
	p := new(Signal)
	*p = x
	return p
}

func (x Signal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Signal) Descriptor() protoreflect.EnumDescriptor {
	return file_sketch_proto_enumTypes[1].Descriptor()
}

func (Signal) Type() protoreflect.EnumType {
	return &file_sketch_proto_enumTypes[1]
}

func (x Signal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Signal.Descriptor instead.
func (Signal) EnumDescriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{1}
}

type Mode int32

const (
	Mode_input  Mode = 0
	Mode_output Mode = 1
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "input",
		1: "output",
	}
	Mode_value = map[string]int32{
		"input":  0,
		"output": 1,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_sketch_proto_enumTypes[2].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_sketch_proto_enumTypes[2]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{2}
}

// Sketch defines how a device is programmed
type Sketch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The toolkit or skillset required to run
	// this sketch core (Nano,Uno), esp32 ()
	Toolkit string `protobuf:"bytes,6,opt,name=toolkit,proto3" json:"toolkit,omitempty"`
	// The label unique to this toolkit
	// eg: "blink"
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// The device activated by this sketch
	// eg: "/home-iot/devices/esp32-01"
	Device string `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	// The purpose or description of the actions take by this sketch
	// eg: "Blink at prescribed intervals"
	Purpose string `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	// The setup stage defines the actions to take once
	// before entering the sketch loop
	Setup []*Action `protobuf:"bytes,4,rep,name=setup,proto3" json:"setup,omitempty"`
	// The loop defines the actions that repeats forever
	Loop []*Action `protobuf:"bytes,5,rep,name=loop,proto3" json:"loop,omitempty"`
}

func (x *Sketch) Reset() {
	*x = Sketch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sketch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sketch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sketch) ProtoMessage() {}

func (x *Sketch) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sketch.ProtoReflect.Descriptor instead.
func (*Sketch) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{0}
}

func (x *Sketch) GetToolkit() string {
	if x != nil {
		return x.Toolkit
	}
	return ""
}

func (x *Sketch) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Sketch) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Sketch) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *Sketch) GetSetup() []*Action {
	if x != nil {
		return x.Setup
	}
	return nil
}

func (x *Sketch) GetLoop() []*Action {
	if x != nil {
		return x.Loop
	}
	return nil
}

// Action defines a processing step or instruction
type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The sequence defines the order of steps
	Sequence int32 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// The type identifies the type of command to run
	Type ActionType `protobuf:"varint,2,opt,name=type,proto3,enum=centretown.sketchit.v1.ActionType" json:"type,omitempty"`
	// command defines one of a menu of commands to take
	//
	// Types that are assignable to Operation:
	//	*Action_Delay
	//	*Action_Mode
	//	*Action_Pin
	Operation isAction_Operation `protobuf_oneof:"operation"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sketch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Action) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_delay
}

func (m *Action) GetOperation() isAction_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (x *Action) GetDelay() *DelayOperation {
	if x, ok := x.GetOperation().(*Action_Delay); ok {
		return x.Delay
	}
	return nil
}

func (x *Action) GetMode() *ModeOperation {
	if x, ok := x.GetOperation().(*Action_Mode); ok {
		return x.Mode
	}
	return nil
}

func (x *Action) GetPin() *PinOperation {
	if x, ok := x.GetOperation().(*Action_Pin); ok {
		return x.Pin
	}
	return nil
}

type isAction_Operation interface {
	isAction_Operation()
}

type Action_Delay struct {
	Delay *DelayOperation `protobuf:"bytes,10,opt,name=delay,proto3,oneof"`
}

type Action_Mode struct {
	Mode *ModeOperation `protobuf:"bytes,11,opt,name=mode,proto3,oneof"`
}

type Action_Pin struct {
	Pin *PinOperation `protobuf:"bytes,12,opt,name=pin,proto3,oneof"`
}

func (*Action_Delay) isAction_Operation() {}

func (*Action_Mode) isAction_Operation() {}

func (*Action_Pin) isAction_Operation() {}

// DelayOperation defines the data to carry out this action
type DelayOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The duration of the delay in milliseconds
	Duration int32 `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *DelayOperation) Reset() {
	*x = DelayOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sketch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelayOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayOperation) ProtoMessage() {}

func (x *DelayOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayOperation.ProtoReflect.Descriptor instead.
func (*DelayOperation) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{2}
}

func (x *DelayOperation) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// ModeOperation defines how a pin is acted on.
type ModeOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The pin id
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The signal type analog/digital
	Signal Signal `protobuf:"varint,2,opt,name=signal,proto3,enum=centretown.sketchit.v1.Signal" json:"signal,omitempty"`
	// The mode type output/input
	Mode Mode `protobuf:"varint,3,opt,name=mode,proto3,enum=centretown.sketchit.v1.Mode" json:"mode,omitempty"`
}

func (x *ModeOperation) Reset() {
	*x = ModeOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sketch_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModeOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeOperation) ProtoMessage() {}

func (x *ModeOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeOperation.ProtoReflect.Descriptor instead.
func (*ModeOperation) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{3}
}

func (x *ModeOperation) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModeOperation) GetSignal() Signal {
	if x != nil {
		return x.Signal
	}
	return Signal_analog
}

func (x *ModeOperation) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_input
}

// PinOperation reads/writes analog/digital values
type PinOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The pin id
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The signal type analog/digita
	Signal Signal `protobuf:"varint,2,opt,name=signal,proto3,enum=centretown.sketchit.v1.Signal" json:"signal,omitempty"`
	// The mode type output/input
	Mode Mode `protobuf:"varint,3,opt,name=mode,proto3,enum=centretown.sketchit.v1.Mode" json:"mode,omitempty"`
	// The value to read from or write to
	Value int32 `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PinOperation) Reset() {
	*x = PinOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sketch_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PinOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinOperation) ProtoMessage() {}

func (x *PinOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinOperation.ProtoReflect.Descriptor instead.
func (*PinOperation) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{4}
}

func (x *PinOperation) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PinOperation) GetSignal() Signal {
	if x != nil {
		return x.Signal
	}
	return Signal_analog
}

func (x *PinOperation) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_input
}

func (x *PinOperation) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_sketch_proto protoreflect.FileDescriptor

var file_sketch_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16,
	0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63,
	0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x0c, 0x64, 0x65, 0x70, 0x75, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd4, 0x01, 0x0a, 0x06, 0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x74, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x75, 0x72, 0x70, 0x6f,
	0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73,
	0x65, 0x12, 0x34, 0x0a, 0x05, 0x73, 0x65, 0x74, 0x75, 0x70, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b,
	0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x05, 0x73, 0x65, 0x74, 0x75, 0x70, 0x12, 0x32, 0x0a, 0x04, 0x6c, 0x6f, 0x6f, 0x70, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f,
	0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x6c, 0x6f, 0x6f, 0x70, 0x22, 0xa0, 0x02, 0x0a, 0x06,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x36, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x22, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b,
	0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3e, 0x0a, 0x05, 0x64, 0x65,
	0x6c, 0x61, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x65, 0x6e, 0x74,
	0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x48, 0x00, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x3b, 0x0a, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72,
	0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x00, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x38, 0x0a, 0x03, 0x70, 0x69, 0x6e, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77,
	0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69,
	0x6e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x03, 0x70, 0x69,
	0x6e, 0x42, 0x0b, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2c,
	0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x89, 0x01, 0x0a,
	0x0d, 0x4d, 0x6f, 0x64, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x36,
	0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e,
	0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74,
	0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x06,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x30, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77,
	0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x9e, 0x01, 0x0a, 0x0c, 0x50, 0x69, 0x6e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x06, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x63, 0x65, 0x6e, 0x74,
	0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x12, 0x30, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1c, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65,
	0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0x2a, 0x0a, 0x0a, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x64, 0x65, 0x6c, 0x61, 0x79,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03,
	0x70, 0x69, 0x6e, 0x10, 0x02, 0x2a, 0x21, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12,
	0x0a, 0x0a, 0x06, 0x61, 0x6e, 0x61, 0x6c, 0x6f, 0x67, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x64,
	0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x10, 0x01, 0x2a, 0x1d, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65,
	0x12, 0x09, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x10, 0x01, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e,
	0x2f, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x50, 0x00, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sketch_proto_rawDescOnce sync.Once
	file_sketch_proto_rawDescData = file_sketch_proto_rawDesc
)

func file_sketch_proto_rawDescGZIP() []byte {
	file_sketch_proto_rawDescOnce.Do(func() {
		file_sketch_proto_rawDescData = protoimpl.X.CompressGZIP(file_sketch_proto_rawDescData)
	})
	return file_sketch_proto_rawDescData
}

var file_sketch_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sketch_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sketch_proto_goTypes = []interface{}{
	(ActionType)(0),        // 0: centretown.sketchit.v1.ActionType
	(Signal)(0),            // 1: centretown.sketchit.v1.Signal
	(Mode)(0),              // 2: centretown.sketchit.v1.Mode
	(*Sketch)(nil),         // 3: centretown.sketchit.v1.Sketch
	(*Action)(nil),         // 4: centretown.sketchit.v1.Action
	(*DelayOperation)(nil), // 5: centretown.sketchit.v1.DelayOperation
	(*ModeOperation)(nil),  // 6: centretown.sketchit.v1.ModeOperation
	(*PinOperation)(nil),   // 7: centretown.sketchit.v1.PinOperation
}
var file_sketch_proto_depIdxs = []int32{
	4,  // 0: centretown.sketchit.v1.Sketch.setup:type_name -> centretown.sketchit.v1.Action
	4,  // 1: centretown.sketchit.v1.Sketch.loop:type_name -> centretown.sketchit.v1.Action
	0,  // 2: centretown.sketchit.v1.Action.type:type_name -> centretown.sketchit.v1.ActionType
	5,  // 3: centretown.sketchit.v1.Action.delay:type_name -> centretown.sketchit.v1.DelayOperation
	6,  // 4: centretown.sketchit.v1.Action.mode:type_name -> centretown.sketchit.v1.ModeOperation
	7,  // 5: centretown.sketchit.v1.Action.pin:type_name -> centretown.sketchit.v1.PinOperation
	1,  // 6: centretown.sketchit.v1.ModeOperation.signal:type_name -> centretown.sketchit.v1.Signal
	2,  // 7: centretown.sketchit.v1.ModeOperation.mode:type_name -> centretown.sketchit.v1.Mode
	1,  // 8: centretown.sketchit.v1.PinOperation.signal:type_name -> centretown.sketchit.v1.Signal
	2,  // 9: centretown.sketchit.v1.PinOperation.mode:type_name -> centretown.sketchit.v1.Mode
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_sketch_proto_init() }
func file_sketch_proto_init() {
	if File_sketch_proto != nil {
		return
	}
	file_deputy_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_sketch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sketch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sketch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sketch_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelayOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sketch_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModeOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sketch_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PinOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sketch_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Action_Delay)(nil),
		(*Action_Mode)(nil),
		(*Action_Pin)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sketch_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sketch_proto_goTypes,
		DependencyIndexes: file_sketch_proto_depIdxs,
		EnumInfos:         file_sketch_proto_enumTypes,
		MessageInfos:      file_sketch_proto_msgTypes,
	}.Build()
	File_sketch_proto = out.File
	file_sketch_proto_rawDesc = nil
	file_sketch_proto_goTypes = nil
	file_sketch_proto_depIdxs = nil
}
