// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: sketch.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ActionType int32

const (
	ActionType_delay ActionType = 0
	ActionType_mode  ActionType = 1
	ActionType_pin   ActionType = 2
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "delay",
		1: "mode",
		2: "pin",
	}
	ActionType_value = map[string]int32{
		"delay": 0,
		"mode":  1,
		"pin":   2,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_sketch_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_sketch_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{0}
}

type Signal int32

const (
	Signal_analog  Signal = 0
	Signal_digital Signal = 1
)

// Enum value maps for Signal.
var (
	Signal_name = map[int32]string{
		0: "analog",
		1: "digital",
	}
	Signal_value = map[string]int32{
		"analog":  0,
		"digital": 1,
	}
)

func (x Signal) Enum() *Signal {
	p := new(Signal)
	*p = x
	return p
}

func (x Signal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Signal) Descriptor() protoreflect.EnumDescriptor {
	return file_sketch_proto_enumTypes[1].Descriptor()
}

func (Signal) Type() protoreflect.EnumType {
	return &file_sketch_proto_enumTypes[1]
}

func (x Signal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Signal.Descriptor instead.
func (Signal) EnumDescriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{1}
}

type Mode int32

const (
	Mode_input  Mode = 0
	Mode_output Mode = 1
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "input",
		1: "output",
	}
	Mode_value = map[string]int32{
		"input":  0,
		"output": 1,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_sketch_proto_enumTypes[2].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_sketch_proto_enumTypes[2]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{2}
}

// Sketch defines how a device is programmed
type Sketch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The model of the device this sketch is intended to run on
	// eg: ESP32, NANO, UNO
	Model string `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	// The unique label assigned to this sketch
	// eg: "blink"
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// The device activated by this sketch
	// eg: "/home-iot/devices/esp32-01"
	Device string `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	// The purpose or description of the actions take by this sketch
	// eg: "Blink at prescribed intervals"
	Purpose string `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	// The setup stage defines the actions to take once
	// before entering the sketch loop
	Setup []*Action `protobuf:"bytes,4,rep,name=setup,proto3" json:"setup,omitempty"`
	// The loop defines the actions that repeats forever
	Loop []*Action `protobuf:"bytes,5,rep,name=loop,proto3" json:"loop,omitempty"`
}

func (x *Sketch) Reset() {
	*x = Sketch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sketch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sketch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sketch) ProtoMessage() {}

func (x *Sketch) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sketch.ProtoReflect.Descriptor instead.
func (*Sketch) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{0}
}

func (x *Sketch) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Sketch) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Sketch) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Sketch) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *Sketch) GetSetup() []*Action {
	if x != nil {
		return x.Setup
	}
	return nil
}

func (x *Sketch) GetLoop() []*Action {
	if x != nil {
		return x.Loop
	}
	return nil
}

// ListSketchesRequest defines the data required to get a list of sketches
type ListSketchesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The parent model, eg: "ESP32".
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// format and projections...
	Presentation []*Presentation `protobuf:"bytes,4,rep,name=presentation,proto3" json:"presentation,omitempty"`
	// The maximum number of sketches to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The next_page_token value returned from a previous List request, if any.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
}

func (x *ListSketchesRequest) Reset() {
	*x = ListSketchesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sketch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSketchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSketchesRequest) ProtoMessage() {}

func (x *ListSketchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSketchesRequest.ProtoReflect.Descriptor instead.
func (*ListSketchesRequest) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{1}
}

func (x *ListSketchesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListSketchesRequest) GetPresentation() []*Presentation {
	if x != nil {
		return x.Presentation
	}
	return nil
}

func (x *ListSketchesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSketchesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// GetSketchRequest defines the data required to get a Sketch
type GetSketchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The Sketch path name,
	// eg: "/models/ESP32/sketches/esp32-01"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetSketchRequest) Reset() {
	*x = GetSketchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sketch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSketchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSketchRequest) ProtoMessage() {}

func (x *GetSketchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSketchRequest.ProtoReflect.Descriptor instead.
func (*GetSketchRequest) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{2}
}

func (x *GetSketchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ListSketchesResponse defines the return value to a ListsketchesRequest
type ListSketchesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// sketches listed
	Sketches []*Sketch `protobuf:"bytes,1,rep,name=sketches,proto3" json:"sketches,omitempty"`
	// next page
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
}

func (x *ListSketchesResponse) Reset() {
	*x = ListSketchesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sketch_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSketchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSketchesResponse) ProtoMessage() {}

func (x *ListSketchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSketchesResponse.ProtoReflect.Descriptor instead.
func (*ListSketchesResponse) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{3}
}

func (x *ListSketchesResponse) GetSketches() []*Sketch {
	if x != nil {
		return x.Sketches
	}
	return nil
}

func (x *ListSketchesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// CreateSketchRequest defines the data required to create a new Sketch
type CreateSketchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The parent model name
	// eg: /models/ESP32
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The Sketch resource to create.
	Sketch *Sketch `protobuf:"bytes,2,opt,name=Sketch,proto3" json:"Sketch,omitempty"`
}

func (x *CreateSketchRequest) Reset() {
	*x = CreateSketchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sketch_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSketchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSketchRequest) ProtoMessage() {}

func (x *CreateSketchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSketchRequest.ProtoReflect.Descriptor instead.
func (*CreateSketchRequest) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSketchRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateSketchRequest) GetSketch() *Sketch {
	if x != nil {
		return x.Sketch
	}
	return nil
}

// UpdateSketchRequest defines the data required to update an existing Sketch
type UpdateSketchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The Sketch path name,
	// eg: "/models/ESP32/sketches/esp32-01"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The replacement Sketch
	Sketch *Sketch `protobuf:"bytes,2,opt,name=Sketch,proto3" json:"Sketch,omitempty"`
}

func (x *UpdateSketchRequest) Reset() {
	*x = UpdateSketchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sketch_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSketchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSketchRequest) ProtoMessage() {}

func (x *UpdateSketchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSketchRequest.ProtoReflect.Descriptor instead.
func (*UpdateSketchRequest) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSketchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSketchRequest) GetSketch() *Sketch {
	if x != nil {
		return x.Sketch
	}
	return nil
}

// DeleteSketchRequest defines the data required to delete an existing Sketch
type DeleteSketchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The Sketch path name,
	// eg: "/models/ESP32/sketches/esp32-01"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeleteSketchRequest) Reset() {
	*x = DeleteSketchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sketch_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSketchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSketchRequest) ProtoMessage() {}

func (x *DeleteSketchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSketchRequest.ProtoReflect.Descriptor instead.
func (*DeleteSketchRequest) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSketchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Action defines a processing step or instruction
type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The sequence defines the order of steps
	Sequence int32 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// The type identifies the type of command to run
	Type ActionType `protobuf:"varint,2,opt,name=type,proto3,enum=centretown.sketchit.v1.ActionType" json:"type,omitempty"`
	// command defines one of a menu of commands to take
	//
	// Types that are assignable to Operation:
	//	*Action_Delay
	//	*Action_Mode
	//	*Action_Pin
	Operation isAction_Operation `protobuf_oneof:"operation"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sketch_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{7}
}

func (x *Action) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Action) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_delay
}

func (m *Action) GetOperation() isAction_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (x *Action) GetDelay() *DelayOperation {
	if x, ok := x.GetOperation().(*Action_Delay); ok {
		return x.Delay
	}
	return nil
}

func (x *Action) GetMode() *ModeOperation {
	if x, ok := x.GetOperation().(*Action_Mode); ok {
		return x.Mode
	}
	return nil
}

func (x *Action) GetPin() *PinOperation {
	if x, ok := x.GetOperation().(*Action_Pin); ok {
		return x.Pin
	}
	return nil
}

type isAction_Operation interface {
	isAction_Operation()
}

type Action_Delay struct {
	Delay *DelayOperation `protobuf:"bytes,10,opt,name=delay,proto3,oneof"`
}

type Action_Mode struct {
	Mode *ModeOperation `protobuf:"bytes,11,opt,name=mode,proto3,oneof"`
}

type Action_Pin struct {
	Pin *PinOperation `protobuf:"bytes,12,opt,name=pin,proto3,oneof"`
}

func (*Action_Delay) isAction_Operation() {}

func (*Action_Mode) isAction_Operation() {}

func (*Action_Pin) isAction_Operation() {}

// DelayOperation defines the data to carry out this action
type DelayOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The duration of the delay in milliseconds
	Duration int32 `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *DelayOperation) Reset() {
	*x = DelayOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sketch_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelayOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayOperation) ProtoMessage() {}

func (x *DelayOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayOperation.ProtoReflect.Descriptor instead.
func (*DelayOperation) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{8}
}

func (x *DelayOperation) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// ModeOperation defines how a pin is acted on.
type ModeOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The pin id
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The signal type analog/digital
	Signal Signal `protobuf:"varint,2,opt,name=signal,proto3,enum=centretown.sketchit.v1.Signal" json:"signal,omitempty"`
	// The mode type output/input
	Mode Mode `protobuf:"varint,3,opt,name=mode,proto3,enum=centretown.sketchit.v1.Mode" json:"mode,omitempty"`
}

func (x *ModeOperation) Reset() {
	*x = ModeOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sketch_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModeOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeOperation) ProtoMessage() {}

func (x *ModeOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeOperation.ProtoReflect.Descriptor instead.
func (*ModeOperation) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{9}
}

func (x *ModeOperation) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModeOperation) GetSignal() Signal {
	if x != nil {
		return x.Signal
	}
	return Signal_analog
}

func (x *ModeOperation) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_input
}

// PinOperation reads/writes analog/digital values
type PinOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The pin id
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The signal type analog/digita
	Signal Signal `protobuf:"varint,2,opt,name=signal,proto3,enum=centretown.sketchit.v1.Signal" json:"signal,omitempty"`
	// The mode type output/input
	Mode Mode `protobuf:"varint,3,opt,name=mode,proto3,enum=centretown.sketchit.v1.Mode" json:"mode,omitempty"`
	// The value to read from or write to
	Value int32 `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PinOperation) Reset() {
	*x = PinOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sketch_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PinOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinOperation) ProtoMessage() {}

func (x *PinOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinOperation.ProtoReflect.Descriptor instead.
func (*PinOperation) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{10}
}

func (x *PinOperation) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PinOperation) GetSignal() Signal {
	if x != nil {
		return x.Signal
	}
	return Signal_analog
}

func (x *PinOperation) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_input
}

func (x *PinOperation) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_sketch_proto protoreflect.FileDescriptor

var file_sketch_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16,
	0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63,
	0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd0, 0x01, 0x0a, 0x06, 0x53, 0x6b, 0x65, 0x74,
	0x63, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x16,
	0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65,
	0x12, 0x34, 0x0a, 0x05, 0x73, 0x65, 0x74, 0x75, 0x70, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65,
	0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x05, 0x73, 0x65, 0x74, 0x75, 0x70, 0x12, 0x32, 0x0a, 0x04, 0x6c, 0x6f, 0x6f, 0x70, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77,
	0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x6c, 0x6f, 0x6f, 0x70, 0x22, 0xb3, 0x01, 0x0a, 0x13, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x48, 0x0a, 0x0c, 0x70, 0x72,
	0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b,
	0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x26, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x7a, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3a, 0x0a, 0x08, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e,
	0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6b, 0x65, 0x74,
	0x63, 0x68, 0x52, 0x08, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0f,
	0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x65, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6b,
	0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x06, 0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e,
	0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6b, 0x65,
	0x74, 0x63, 0x68, 0x52, 0x06, 0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x22, 0x61, 0x0a, 0x13, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x53, 0x6b, 0x65, 0x74, 0x63, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74,
	0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x52, 0x06, 0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x22, 0x29,
	0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xa0, 0x02, 0x0a, 0x06, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x12, 0x36, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22,
	0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74,
	0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3e, 0x0a, 0x05, 0x64, 0x65, 0x6c, 0x61,
	0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65,
	0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x00, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x3b, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74,
	0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x6f, 0x64, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52,
	0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x38, 0x0a, 0x03, 0x70, 0x69, 0x6e, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e,
	0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x03, 0x70, 0x69, 0x6e, 0x42,
	0x0b, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2c, 0x0a, 0x0e,
	0x44, 0x65, 0x6c, 0x61, 0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x89, 0x01, 0x0a, 0x0d, 0x4d,
	0x6f, 0x64, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x06,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x63,
	0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68,
	0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x06, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x12, 0x30, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e,
	0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x64, 0x65,
	0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x9e, 0x01, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65,
	0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12,
	0x30, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e,
	0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63,
	0x68, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0x2a, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x70, 0x69,
	0x6e, 0x10, 0x02, 0x2a, 0x21, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x0a, 0x0a,
	0x06, 0x61, 0x6e, 0x61, 0x6c, 0x6f, 0x67, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x64, 0x69, 0x67,
	0x69, 0x74, 0x61, 0x6c, 0x10, 0x01, 0x2a, 0x1d, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x09,
	0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x10, 0x01, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x2f, 0x73,
	0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x50, 0x00, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sketch_proto_rawDescOnce sync.Once
	file_sketch_proto_rawDescData = file_sketch_proto_rawDesc
)

func file_sketch_proto_rawDescGZIP() []byte {
	file_sketch_proto_rawDescOnce.Do(func() {
		file_sketch_proto_rawDescData = protoimpl.X.CompressGZIP(file_sketch_proto_rawDescData)
	})
	return file_sketch_proto_rawDescData
}

var file_sketch_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sketch_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_sketch_proto_goTypes = []interface{}{
	(ActionType)(0),              // 0: centretown.sketchit.v1.ActionType
	(Signal)(0),                  // 1: centretown.sketchit.v1.Signal
	(Mode)(0),                    // 2: centretown.sketchit.v1.Mode
	(*Sketch)(nil),               // 3: centretown.sketchit.v1.Sketch
	(*ListSketchesRequest)(nil),  // 4: centretown.sketchit.v1.ListSketchesRequest
	(*GetSketchRequest)(nil),     // 5: centretown.sketchit.v1.GetSketchRequest
	(*ListSketchesResponse)(nil), // 6: centretown.sketchit.v1.ListSketchesResponse
	(*CreateSketchRequest)(nil),  // 7: centretown.sketchit.v1.CreateSketchRequest
	(*UpdateSketchRequest)(nil),  // 8: centretown.sketchit.v1.UpdateSketchRequest
	(*DeleteSketchRequest)(nil),  // 9: centretown.sketchit.v1.DeleteSketchRequest
	(*Action)(nil),               // 10: centretown.sketchit.v1.Action
	(*DelayOperation)(nil),       // 11: centretown.sketchit.v1.DelayOperation
	(*ModeOperation)(nil),        // 12: centretown.sketchit.v1.ModeOperation
	(*PinOperation)(nil),         // 13: centretown.sketchit.v1.PinOperation
	(*Presentation)(nil),         // 14: centretown.sketchit.v1.Presentation
}
var file_sketch_proto_depIdxs = []int32{
	10, // 0: centretown.sketchit.v1.Sketch.setup:type_name -> centretown.sketchit.v1.Action
	10, // 1: centretown.sketchit.v1.Sketch.loop:type_name -> centretown.sketchit.v1.Action
	14, // 2: centretown.sketchit.v1.ListSketchesRequest.presentation:type_name -> centretown.sketchit.v1.Presentation
	3,  // 3: centretown.sketchit.v1.ListSketchesResponse.sketches:type_name -> centretown.sketchit.v1.Sketch
	3,  // 4: centretown.sketchit.v1.CreateSketchRequest.Sketch:type_name -> centretown.sketchit.v1.Sketch
	3,  // 5: centretown.sketchit.v1.UpdateSketchRequest.Sketch:type_name -> centretown.sketchit.v1.Sketch
	0,  // 6: centretown.sketchit.v1.Action.type:type_name -> centretown.sketchit.v1.ActionType
	11, // 7: centretown.sketchit.v1.Action.delay:type_name -> centretown.sketchit.v1.DelayOperation
	12, // 8: centretown.sketchit.v1.Action.mode:type_name -> centretown.sketchit.v1.ModeOperation
	13, // 9: centretown.sketchit.v1.Action.pin:type_name -> centretown.sketchit.v1.PinOperation
	1,  // 10: centretown.sketchit.v1.ModeOperation.signal:type_name -> centretown.sketchit.v1.Signal
	2,  // 11: centretown.sketchit.v1.ModeOperation.mode:type_name -> centretown.sketchit.v1.Mode
	1,  // 12: centretown.sketchit.v1.PinOperation.signal:type_name -> centretown.sketchit.v1.Signal
	2,  // 13: centretown.sketchit.v1.PinOperation.mode:type_name -> centretown.sketchit.v1.Mode
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_sketch_proto_init() }
func file_sketch_proto_init() {
	if File_sketch_proto != nil {
		return
	}
	file_commander_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_sketch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sketch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sketch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSketchesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sketch_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSketchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sketch_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSketchesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sketch_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSketchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sketch_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSketchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sketch_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSketchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sketch_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sketch_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelayOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sketch_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModeOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sketch_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PinOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sketch_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*Action_Delay)(nil),
		(*Action_Mode)(nil),
		(*Action_Pin)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sketch_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sketch_proto_goTypes,
		DependencyIndexes: file_sketch_proto_depIdxs,
		EnumInfos:         file_sketch_proto_enumTypes,
		MessageInfos:      file_sketch_proto_msgTypes,
	}.Build()
	File_sketch_proto = out.File
	file_sketch_proto_rawDesc = nil
	file_sketch_proto_goTypes = nil
	file_sketch_proto_depIdxs = nil
}
